### ISSUE TITLE
got a crash report for you

### ISSUE THREAD

**Issue by superon** [DrexHD/VillagerFix#11]
https://pastebin.com/SEfnzHhP
happens with latest version mod version before this is fine it seems

**Comment by superon** [comment]
actually last version i have that doesn't crash the pack is villagerfix-1.4.1+1.16.2-1.16.4

**Comment by DrexHD** [comment]
You didn't send the entire crash report, what you sent doesn't really help for debugging!

**Comment by superon** [comment]
:/ sorry, that was from console... how's this?
https://pastebin.com/6r9mKWv1

**Comment by DrexHD** [comment]
This seems to be a compatability issue with MCDungeonsArmors, which attempts to add their own custom trades.

**Comment by chronosacaria** [comment]
Is this an issue that would need to be fixed from my end or yours? I thought that the way I implemented the custom trades was the most common way, but it wouldn't be the first time I was wrong. Is there a more appropriate way that I should be adding custom trades? Thanks, in advance!

**Comment by DrexHD** [comment]
Hi, your way of implementing the trades is fine. The problem is, my mod expects all "TradeFactories" to implement [JsonSerializer](https://github.com/DrexHD/VillagerFix/blob/master/src/main/java/me/drex/villagerfix/villager/types/JsonSerializer.java), so it can automatically generate a file with all villager trades. The problem is that your [BasicTradeFactory](https://github.com/chronosacaria/MCDungeonsArmors/blob/main/src/main/java/chronosacaria/mcda/factories/BasicTradeFactory.java) doesn't implement that interface (obviously).
From the top of my head these would be some solutions for the compatability of our mods:
- I ignore all custom trade factories in my trader serializer -> custom trades like yours disappear from villager trades
- I add a custom trade factory (which implements JsonSerializer) that you could use that let's you specify all aspects of trades. -> Your mod would either have to depend on mine :| or somehow check if it is loaded and it that case use that custom trade factory
- You could use vanillas `SellItemFactory` -> Everything should work as expected, BUT because of the nature of it, you can only use emeralds (no emerald blocks) as currency, which leads to a maximum of 64 emeralds instead of your 90 (10 emerald blocks)
- You could try to check if my mod is loaded and if it is implement my JsonSerializer yourself

**Comment by DrexHD** [comment]
@chronosacaria

**Comment by chronosacaria** [comment]
Hey, DrexHD! Sorry I couldn't respond earlier. Work was insane this week. I will try to rework the trades using the `SellItemFactory` and see if I like the economic impacts of that, especially as I had not considered what how obscene some of the discounts would be with Hero of the Village using Emerald Blocks. So I'll probably just implement that suggestion, which I am really grateful for :)
