### ISSUE TITLE
NoSuchFileException for VillagerData/Wandering_Trader.json

### ISSUE THREAD

**Issue by MobButcher** [DrexHD/VillagerFix#18]
When Wandering trader spawns, I get this error in the console:

```[17:50:47] [Server thread/ERROR]: Couldn't load Wandering_Trader.jsonjava.nio.file.NoSuchFileException: ./config/VillagerData/Wandering_Trader.json```

The file exists in the config folders, but the pathfile on the file system is all lowercase. Because of this it seems like I can't trade with the wandering villager and their llamas don't have any capacity in them.

**Comment by DrexHD** [comment]
I fixed this issue a couple of weeks ago, but am unable to upload this fix to curseforge, because their file detection system detects it as copy of the previous version (change in code is to small)
You can either rename your `wandering_trader.json` file to `Wandering_Trader.json` or get the fixed version from the [github actions](https://pipelines.actions.githubusercontent.com/5GyWZpUvnHcls4yOaTgA2IgZESQSbRtgDMrX2E1nLYbsBa5uZ7/_apis/pipelines/1/runs/20/signedartifactscontent?artifactName=Artifacts&urlExpires=2021-08-10T15%3A18%3A30.6471251Z&urlSigningMethod=HMACV1&urlSignature=iLeXP%2FzReff4GyWDC%2BY01YHqsoebE7syVyumKjG2Kzc%3D) to fix your issue.
